DJANGO_SECRET_KEY = 'YOU NEED TO MAKE A NEW SECRET KEY HERE'

# Heroku related sensitive data
HEROKU_APP_URL = 'YOUR HEROKU APP URL HERE'
HEROKU_DB_NAME = 'THE NAME OF YOUR DATABASE'
HEROKU_DB_USER = 'YOUR USERNAME FOR YOUR DB'
HEROKU_DB_PWD = 'YOUR DB PASSWORD'
HEROKU_DB_HOST = ''
HEROKU_DB_PORT = ''

# Local sensitive data
LOCAL_DB_NAME = 'THE NAME OF YOUR DATABASE'
LOCAL_DB_USER = 'YOUR USERNAME FOR YOUR DB'
LOCAL_DB_PWD = 'YOUR DB PASSWORD'
LOCAL_DB_HOST = ''
LOCAL_DB_PORT = ''
